// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc6r6f3jek-M0yrEGiUsWsLKw5PTyG6zY',
    appId: '1:168734480351:web:72ca3e8dd0b8459849966a',
    messagingSenderId: '168734480351',
    projectId: 'emart-a19b3',
    authDomain: 'emart-a19b3.firebaseapp.com',
    storageBucket: 'emart-a19b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGLyq9gK-wrbUQMq_w1vaTJ0_ObYk_4Zs',
    appId: '1:168734480351:android:cb039a6ff6ff46ef49966a',
    messagingSenderId: '168734480351',
    projectId: 'emart-a19b3',
    storageBucket: 'emart-a19b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG64s_nKLhjpimkaxbQXiV2NY1Gx6Pkqg',
    appId: '1:168734480351:ios:2c0f8bacebef8ae249966a',
    messagingSenderId: '168734480351',
    projectId: 'emart-a19b3',
    storageBucket: 'emart-a19b3.appspot.com',
    androidClientId: '168734480351-e0uo1evf8ijjcsfu9q7e6dqhc474h7a2.apps.googleusercontent.com',
    iosClientId: '168734480351-0r7ru3f9heve75veme9lfhjg5cjj49vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG64s_nKLhjpimkaxbQXiV2NY1Gx6Pkqg',
    appId: '1:168734480351:ios:2c0f8bacebef8ae249966a',
    messagingSenderId: '168734480351',
    projectId: 'emart-a19b3',
    storageBucket: 'emart-a19b3.appspot.com',
    androidClientId: '168734480351-e0uo1evf8ijjcsfu9q7e6dqhc474h7a2.apps.googleusercontent.com',
    iosClientId: '168734480351-0r7ru3f9heve75veme9lfhjg5cjj49vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoping',
  );
}
